---
- name: Create Citrix Site
  citrix_site:
    name: "{{ citrix.site }}"
    db_server: "{{ citrix_site_DatabaseServer }}"
    db_port: "{{ citrix_site_DatabaseServerPort }}"
    admin_group: "{{ citrix_site_AdminGroup }}"
    state: present
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_password: "{{ ansible_password }}"

- name: Set the Citrix License Server
  citrix_license:
    lic_server: "{{ citrix_site_LicenseServer }}"
    lic_port: "{{ citrix_site_LicenseServerPort }}"
    lic_model: "{{ citrix_site_LicensingModel }}"  
    lic_product_code: "{{ citrix_site_ProductCode }}"    
    lic_product_edition: "{{ citrix_site_ProductEdition }}"
    state: present
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_password: "{{ ansible_password }}"