---
  - name: Get username
    ansible.windows.win_powershell:
      script: |
        write-output $(whoami)
    register: PS_output

  - name: Output Username
    debug:
      var: PS_output

  - name: Import PS Snapins for Citrix
    ansible.windows.win_powershell:
      script: |
        Add-PSSnapIn citrix*
        Import-Module citrix*

  - name: Import PS Snapins for Citrix
    ansible.windows.win_powershell:
      script: |
        Get-Command *XDD*
    register: GC_output

  - name: Output Snapins and Modules
    debug:
      var: GC_output